export const SLOGANS = [
  'Discover the perfect blend of style and comfort',
  'Elevate your wardrobe with our latest collection',
  'Experience luxury like never before',
  'Unleash your inner fashionista',
  'Step into the world of elegance and sophistication',
  'Style is a way to say who you are without having to speak',
  'Fashion is what you buy, style is what you do with it',
  'Life is too short to wear boring clothes',
  'Fashion fades, only style remains the same',
  'Dress shabbily and they remember the dress; dress impeccably and they remember the woman',
  'Fashion is about something that comes from within you',
  'Fashion is the armor to survive the reality of everyday life',
  'I like my money right where I can see it: hanging in my closet',
];
